### ISSUE TITLE
Commit issue with husky

### ISSUE THREAD

**Issue by NigelOToole** [nostalgic-css/NES.css#323] opened 2019-03-08 15:37 UTC
I have forked NES.css and tried to commit and go the error below. This seems to be a husky issue but the issue is still open. https://github.com/typicode/husky/issues/390

Can't find node in PATH, trying to find a node binary on your system
husky > pre-commit (node v10.15.0)

**To Reproduce**
1. Try to commit with node v10

**Expected behavior**
Commit as usual.

**Screenshots**

**Environment:**
Mac OSX 10.12.6
Node 10.15

**Comment by guastallaigor** [comment] 2019-03-08 15:51
I wasn't able to replicate this bug.
I can commit successfully using Ubuntu 16.04 and 18.04 using node v10.15.2, see screenshot below:

![image](https://user-images.githubusercontent.com/22016005/54039021-adebdf00-41a0-11e9-8ca9-f5744c2fced8.png)

Maybe this is a Mac OSX situation?

**Comment by BcRikko** [comment] 2019-03-09 00:31
I could not reproduce it too. 🤔 

My env
* macOX High Sierra
* npm: v6.4.1
* node: v10.15.1


Could you check if the PATH of node passes by executing the following command? 🔍 
```bash
echo $PATH
```

If the problem does not reproduce could you try reinstalling `node_modules`?
```bash
rm -rf node_modules
npm i --no-save
```

**Comment by NigelOToole** [comment] 2019-03-11 15:14
The output from echo $PATH is below and reinstalling node_modules didnt help unfortunately. Could it have anything to do with this issue? https://github.com/typicode/husky/issues/390

/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands

**Comment by BcRikko** [comment] 2019-03-12 04:26
Are you trying  to commit using the GUI? (Sourcetree, tower, and so on)
If so, I think this issue is the same problem. 🤔 

Could you open GUI Application from terminal?
Then you can read `.bashrc` or `.bash_profile`, so I think you can solve the node path.

```bash
$ open /Applications/yourappname.app
```

**Comment by NigelOToole** [comment] 2019-03-12 16:38
Im using sourcetree and in the .bash_profile I have the below.

[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

**Comment by BcRikko** [comment] 2019-03-12 22:47
Thanks for the information. 🙇 
This issue is not a problem of NES.css. so I close it.
If you need help, could you write to husky's issue? 🙏

**Closed by BcRikko** 2019-03-12 22:47 UTC
Labels: bug, couldn't reproduce

**Comment by NigelOToole** [comment] 2019-03-13 16:23
I understand, thanks for trying. I may create my own repo with the my suggestions at some stage.

**Comment by NigelOToole** [comment] 2019-04-05 10:23
Hi guys

I have created a repo with the suggested updates to the pixel borders. Its somewhat of a remix of what you have done in NES.css. Please have a look as I hope there are some ideas you guys can use and if I get time I may release as a standalone mixin if thats ok with you.

https://github.com/NigelOToole/pixel-borders
https://nigelotoole.github.io/pixel-borders/
